version: '3.8'

x-common-variables: &common-variables
  DATABASE_URL: postgres://postgres:postgres@db:5432/postgres

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    environment:
      <<: *common-variables
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    command: ["python", "-m", "code.app"]
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres"]

volumes:
  pgdata:
