x-common-variables: &common-variables
  DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
  REDIS_URL: redis://redis:6379
  RABBIT_MQ_URL: amqp://guest:guest@rabbitmq:5672
  OPENAI_API_KEY: '*'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    environment:
      <<: *common-variables
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    command: ["python", "-m", "code.app"]
    depends_on:
      - db
      - redis

  celery:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    environment:
      <<: *common-variables
    volumes:
      - .:/app
    command: ["aio_celery", "worker", "code.celery:app"]
    depends_on:
      - db
      - redis

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres"]

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.11.3-management
    ports:
      - "5672:5672"
      - "15672:15672"
